analyzer:
  errors:
    unused_import: warning
    unused_local_variable: warning
    unused_field: warning
    prefer_expression_function_bodies: warning
    prefer_single_quotes: warning
    prefer_typing_uninitialized_variables: warning
    avoid_init_to_null: warning
    prefer_const_constructors: warning
    prefer_conditional_assignment: warning
    prefer_final_fields: warning
    unnecessary_cast: warning
  exclude:
    - "**/generated/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mockito.dart"
    - "**/*.reflectable.dart"
    - "**/*.template.dart"

include: package:flutter_lints/flutter.yaml